# tekton/tasks/lint.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-code
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        pip install flake8
        echo "Running flake8 linting..."
        flake8 service/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics