# kind-config-v1.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta4
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        runtime-config: "api/all=true"
  extraPortMappings:
  - containerPort: 30080
    hostPort: 18080
    protocol: TCP
  - containerPort: 30432
    hostPort: 15432
    protocol: TCP


